Repository jenkinsci/subversion-plugin, pull requests merged in 2019-12, with the labels that each got.

#239 Fixed some deprecated usages
  src/main/java/hudson/scm/SubversionChangeLogBuilder.java
  src/main/java/hudson/scm/SubversionSCM.java
  src/main/java/hudson/scm/browsers/Sventon.java
  src/main/java/hudson/scm/browsers/Sventon2.java
  src/main/java/hudson/scm/subversion/UpdateUpdater.java
  src/main/java/jenkins/scm/impl/subversion/SubversionSCMSource.java
  src/test/java/hudson/scm/SubversionRepositoryStatusTest.java
  src/test/java/hudson/scm/SubversionSCMUnitTest.java
  src/test/java/hudson/scm/SvnHelperTest.java
  src/test/java/hudson/scm/listtagsparameter/ListSubversionTagsParameterValueTest.java
Labels: chore

#238 Fix FreeBSD12 compatibility problem
  pom.xml
Labels: dependencies

#241 Move documentation from wiki
  README.md
  docs/images/logger.png
  docs/old-changelog.md
  pom.xml
Labels: documentation
